# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-and-test

on:
  push:
  pull_request:
    branches: [ "dev", "master" ]
    paths:
    - '**.cs'
    - '**.csproj'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/OCS.Applications 
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/OCS.Applications 
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/OCS.Applications 
